server:
  port: 7777
  hostname: localhost
  client-port: 8761

spring:
  application:
    name: service-core

eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.hostname}:${server.client-port}/eureka/
